BinLLM/urls.py
from django.urls import path
from . import views


app_name = 'BinLLM'

urlpatterns = [
    # path('', home, name='home'),
    path('', views.index, name='index'),
    path("upload_file", views.upload_file, name='upload_file'),
    path("upload_multi_file", views.upload_multi_file, name='upload_multi_file'),
    path("process_file", views.process_file, name='process_file'),
    path("process_multi_file", views.process_multi_file, name='process_multi_file'),
    path("history", views.history, name='history'),
    path("about", views.about, name='about'),
    path("detailed_file/<str:hash_id>/", views.detailed_file, name='detailed_file'),

    path('delete/<str:hash_id>/',views.file_delete, name='file_delete'),
    path('download/<str:hash_id>/', views.file_download, name='file_download'),
    path('rehandle/<str:hash_id>/', views.file_rehandle, name='file_rehandle')

    # path('list/', views.file_list, name='file_list' ),
    # path('upload/', views.upload_file, name='upload_file' ),
    # path('detail/<int:id>/', views.file_detail, name='file_detail' ),
    #
    # path('error/', views.error, name='error' ),
    #
    # path('download/<int:id>/', views.file_download, name='file_download'),
    # path('delete/<int:id>/',views.file_delete, name='file_delete' ),
    #
    # path('history/', views.recycled_detail, name='recycled_detail'),
]

HOME/urls.py
from django.urls import path
from . import views


app_name = 'HOME'


urlpatterns = [
    path('', views.index, name='index')
]

UI/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path('BinLLM/', include('BinLLM.urls', namespace='BinLLM')),
    path('', include('HOME.urls', namespace='HOME')),
    path('User/', include('User.urls', namespace='User'))
]

User/urls.py
from django.urls import path
from . import views


app_name = 'User'


urlpatterns = [
    path('profile', views.profile, name='profile'),
    path('settings', views.settings, name='settings'),
    path('login/', views.user_login, name='login'),
    path('register/', views.user_register, name='register'),
]

HOME/models.py
from django.db import models

# Create your models here.

HOME/views.py
from django.shortcuts import render

# Create your views here.

def index(request):

    return render(request, "home.html")

HOME/templates/home.html
{% load static %}
<!DOCTYPE HTML>
<!--
	Spectral by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>Spectral by HTML5 UP</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
		<noscript><link rel="stylesheet" href="{% static 'assets/css/noscript.css' %}" /></noscript>
	</head>
	<body class="landing is-preload">

		<!-- Page Wrapper -->
			<div id="page-wrapper">

				<!-- Header -->
					<header id="header" class="alt">
						<h1><a href="{% url 'BinLLM:upload_file' %}">BinLLM</a></h1>
						<nav id="nav">
							<ul>
								<li class="special">
									<a href="#menu" class="menuToggle"><span>菜单</span></a>
									<div id="menu">
										<ul>
											<li><a href="{% url 'BinLLM:upload_file' %}">开始使用</a></li>
											<li><a href="{% url 'User:login' %}">登录账户</a></li>
											<li><a href="{% url 'BinLLM:about' %}">了解更多</a></li>
										</ul>
									</div>
								</li>
							</ul>
						</nav>
					</header>

				<!-- Banner -->
					<section id="banner">
						<div class="inner">
							<h2 style="font-size: 40px">BinLLM</h2>
							<p>Binary Taint Analysis with LLMs<br />基于大语言模型的二进制代码漏洞检测系统.</p>
							<ul class="actions special">
								<li><a href="{% url 'BinLLM:upload_file' %}" class="button warning">开始使用</a></li>
							</ul>
						</div>
						<a href="#one" class="more scrolly">了解更多</a>
					</section>

				<!-- One -->
					<section id="one" class="wrapper style1 special">
						<div class="inner">
							<header class="major">
								<h2>项目介绍<br />
								Introduction</h2>
								<p>
    随着计算机科学技术的发展，软件系统中的漏洞成为网络安全的重大威胁，尤其是在物联网领域。然而，传统的二进制漏洞检测技术存在覆盖率低、依赖人工定义规则、误报率高等问题。
    本团队开发出了一款 <strong style="color:#484a54;">基于大语言模型的二进制代码漏洞检测系统 BinLLM</strong>，旨在提高二进制代码中漏洞检测的准确性和效率.
    结果表明BinLLM在性能上优于现有的检测工具Emtaint和Karonte，并且能够在低性能设备上高效运行，表明BinLLM不仅适用于传统计算环境，也能在资源受限的低功耗设备环境中保持良好的检测性能，具有广泛的应用前景。</p>
                                <img src="{% static '/images/flow.png' %}" style="width: 70%">
							</header>
						</div>
					</section>

				<!-- Two -->
					<section id="two" class="wrapper alt style2">
						<section class="spotlight">
							<div class="image"><img src="{% static 'images/repo.png' %}" alt="" /></div><div class="content">
								<h2 style="color:#707070;">
								    项目背景：软件漏洞风险上升
                                </h2>
								<p>软件漏洞是指软件在其生命周期（即开发、部署、执行整个过程）中存在的缺陷，而这些缺陷可能会被不法分子利用，从而任意操纵系统。
<br />据美国国家漏洞数据库披露的历年漏洞记录数量，2023年披露的漏洞数量相比去年增加了约1500个。</p>
							</div>
						</section>
						<section class="spotlight">
							<div class="image"><img src="{% static 'images/tech.png' %}" alt="" /></div><div class="content">
								<h2 style="color:#707070;">
                                    技术背景：污点分析
                                </h2>
                            <p>通用的二进制污点分析技术包括: ①别污点源和污点汇聚点；②基于定制的污染策略进行污点传播分析；<br />
                                传统方法依靠手工定义/一次性定义规则，存在缺漏和不具有普遍性的缺点</p>
							</div>
						</section>
						<section class="spotlight">
							<div class="image"><img src="{% static 'images/ghidra.png' %}" alt="" /></div><div class="content">
								<h2 style="color:#707070;">
                                    技术背景：二进制反汇编
                                </h2>
								<p>传统反汇编技术，如Ghidra，IDA等，存在可读性差、难以执行、语法错误等问题。</p>
							</div>
						</section>
					</section>

				<!-- Three -->
					<section id="three" class="wrapper style3 special">
						<div class="inner">
							<header class="major">
								<h2 >
                                    项目优势及创新点<br/>
                                    Project Advantages
                                </h2>
								<p>Aliquam ut ex ut augue consectetur interdum. Donec amet imperdiet eleifend<br />
								fringilla tincidunt. Nullam dui leo Aenean mi ligula, rhoncus ullamcorper.</p>
                                <img src="{% static '/images/flow_more.png' %}" style="width: 100%">
							</header>
							<ul class="features">
								<li class="icon fa-paper-plane">
									<h3>Arcu accumsan</h3>
									<p>Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat.</p>
								</li>
								<li class="icon solid fa-laptop">
									<h3>Ac Augue Eget</h3>
									<p>Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat.</p>
								</li>
								<li class="icon solid fa-code">
									<h3>Mus Scelerisque</h3>
									<p>Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat.</p>
								</li>
								<li class="icon solid fa-headphones-alt">
									<h3>Mauris Imperdiet</h3>
									<p>Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat.</p>
								</li>
								<li class="icon fa-heart">
									<h3>Aenean Primis</h3>
									<p>Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat.</p>
								</li>
								<li class="icon fa-flag">
									<h3>Tortor Ut</h3>
									<p>Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat.</p>
								</li>
							</ul>
						</div>
					</section>

				<!-- CTA -->
					<section id="cta" class="wrapper style4">
						<div class="inner">
							<header>
								<h2>BinLLM</h2>
								<p>基于大语言模型的二进制代码漏洞检测系统</p>
							</header>
							<ul class="actions stacked">
								<li><a href="{% url 'BinLLM:upload_file' %}" class="button fit primary">开始使用</a></li>
								<li><a href="{% url 'BinLLM:about' %}" class="button fit">Learn More</a></li>
							</ul>
						</div>
					</section>

				<!-- Footer -->
					<footer id="footer">
						<ul class="copyright">
							<span>Copyright &copy; BinLLM 2024</span>
						</ul>
					</footer>

			</div>

		<!-- Scripts -->
			<script src="{% static 'assets/js/jquery.min.js' %}"></script>
			<script src="{% static 'assets/js/jquery.scrollex.min.js' %}"></script>
			<script src="{% static 'assets/js/jquery.scrolly.min.js' %}"></script>
			<script src="{% static 'assets/js/browser.min.js' %}"></script>
			<script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
			<script src="{% static 'assets/js/util.js' %}"></script>
			<script src="{% static 'assets/js/main.js' %}"></script>

	</body>
</html>