UI/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path('BinLLM/', include('BinLLM.urls', namespace='BinLLM')),
    path('', include('HOME.urls', namespace='HOME')),
    path('User/', include('User.urls', namespace='User'))
]

User/urls.py
from django.urls import path
from . import views


app_name = 'User'


urlpatterns = [
    path('profile', views.profile, name='profile'),
    path('settings', views.settings, name='settings'),
    path('login/', views.user_login, name='login'),
    path('register/', views.user_register, name='register'),
]

User/models.py
from django.db import models

# Create your models here.

class LLMsetting(models.Model):
    CATEGORY_CHOICES = [
        (1, 'deepseek'),
        (2, 'gpt-4o'),
        (3, 'gpt-3.5-turbo')
    ]
    llm_category = models.PositiveSmallIntegerField(choices=CATEGORY_CHOICES, default=1)  # LLM类别
    llm_api = models.CharField(max_length=255, default="添加模型 API")

    llm_token = models.IntegerField(default=4096)
    llm_temp = models.CharField(max_length=20, default="0.9")

    stage1 = models.TextField(default="As a program analyst, I give you snippets of C code generated by decompilation, using {start} as the taint source, and {parameter} marked as the taint label to extract the taint data flow. Pay attention to the data alias and tainted data operations. Output in the form of data flows.")
    stage2 = models.TextField(default="Continue to analyze {function} according to the above taint analysis results. Pay attention to the data alias, tainted data operations, and sources.")
    stage3 = models.TextField(default="Based on the above taint analysis results, analyze whether the code has vulnerabilities. If there is a vulnerability, please explain what kind of vulnerability according to CWE. Think step by step.")

class User(models.Model):

    user_name = models.CharField(max_length=20)
    user_password = models.CharField(max_length=255)
    user_id = models.CharField(max_length=255, unique=True)
    online_id = models.IntegerField(default=99)
    user_email = models.EmailField(max_length=255)
    profile = models.ImageField(upload_to='profile_pictures/', null=True, blank=True) #头像
    api = models.CharField(max_length=255)
    bio = models.TextField(max_length=500, blank=True,null=True) #Self-introduction
    last_login = models.DateTimeField(
        verbose_name='last login',
        auto_now=True
    )
    is_authenticated = models.BooleanField(default=False)

    llm_model = models.OneToOneField(LLMsetting, on_delete=models.CASCADE)

    def __str__(self):
        return self.user_name

User/views.py
from django.http import HttpResponse
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.backends import ModelBackend
import uuid
# from django.contrib.auth.models import User
from .models import User, LLMsetting
import hashlib
# 引入验证登录的装饰器
from django.contrib.auth.decorators import login_required
from captcha.models import CaptchaStore

# 自定义后端
class CustomBackend(ModelBackend):
    def authenticate(self, request, user_email=None, user_password=None, **kwargs):
        try:
            user = User.objects.get(user_email=user_email)
            if user_password == user.user_password:
                return user
        except User.DoesNotExist:
            return None

    def get_user(self, user_id):
        try:
            return User.objects.get(pk=user_id)
        except User.DoesNotExist:
            return None


# 合并登录 / 退出按钮
def user_login(request):
    user = request.user
    # 退出登录
    if user.is_authenticated:
        logout(request)
        return redirect('HOME:index')

    print("user_login")

    print(user.is_authenticated)
    if request.method == 'POST':
        print("收到 POST")
        user_email = request.POST.get('email')
        user_password = request.POST.get('password')
        if user_email is "":
            messages.info(request, "邮箱不可为空！")
            return redirect('User:login')
        if user_password is "":
            messages.info(request, "密码不可为空！")
            return redirect('User:login')
        user_db = authenticate(request, user_email=user_email, user_password=user_password)

        if user_db is not None:
            user_db.is_authenticated = True
            user_db.save()
            login(request, user_db)
            online_id = user.id
            user_db.online_id = online_id
            return redirect('User:profile')  # 重定向到登录后的页面
        else:
            print("not found user!")
            messages.info(request, '邮箱或密码错误！')
            return redirect('User:login')

    elif request.method == 'GET':
        return render(request, 'login.html')
    return HttpResponse("请使用GET或POST请求数据")


def user_register(request):
    if request.method == 'POST':
        user_name = request.POST.get('user_name')
        user_email = request.POST.get('email')
        unique_str = f"{user_name}-{uuid.uuid4()}"
        user_id = hashlib.sha256(unique_str.encode('utf-8')).hexdigest()
        user_password = request.POST.get('password')
        user_password2 = request.POST.get('password2')

        print("user_name", user_name)
        print("user_email", user_email)
        print("user_id", user_id)
        print("user_name", user_name)
        # 检查用户名是否已存在
        if User.objects.filter(user_name=user_name).exists():
            messages.error(request, "用户名已存在")
            return render(request, "register.html") # 假设注册页面的 URL 名称为 'register'

        # 检查电子邮件是否已存在
        if User.objects.filter(user_email=user_email).exists():
            messages.error(request, "邮箱已注册")
            return render(request, "register.html")  # 假设注册页面的 URL 名称为 'register'

        if user_password == user_password2:
            new_llm = LLMsetting()
            new_llm.save()
            new_user = User(
                user_id=user_id,
                user_name=user_name,
                user_email=user_email,
                user_password=user_password,
                profile="images/成员1.jpeg",  # 上传的头像文件路径
                bio="添加你的介绍",
                api="添加模型API",
                llm_model=new_llm,
            )
            new_user.save()
        else:
            messages.error(request, '两次输入密码不一致')
            return render(request, "register.html")

        user = authenticate(request, user_id=user_id, user_email=user_email, user_name=user_name, user_password=user_password)
        print(user)

        return redirect('User:login')

    # 填写表单
    elif request.method == 'GET':
        return render(request, 'register.html')
    else:
        return HttpResponse("请使用GET或POST请求数据")


def profile(request):
    user = request.user
    if not user.is_authenticated:
        messages.error(request, '请先登录！')
        return redirect("User:login")
    if request.method == 'POST':
        print(request.POST)
        user_name = request.POST.get('user_name')
        user_email = request.POST.get('email')
        user_bio = request.POST.get('bio')
        user_id = request.POST.get('user_id')
        old_password = request.POST.get('old_password')
        new_password = request.POST.get('new_password')

        print("change profile")
        print("user_name", user_name)
        print("user_email", user_email)
        print("user_bio", user_bio)

        if user.user_password != old_password:
            print('wrong!')
            messages.error(request, '请输入正确的原密码')
            render(request, 'profile.html', {"user": user})
        elif User.objects.filter(user_email=user_email).exists():
            messages.error(request, '邮箱已经被使用过了')
            render(request, 'profile.html', {"user": user})
        else:
            print('start change')
            if new_password:
                user.user_password = new_password
            if user_email:
                user.user_email = user_email
            if user_name:
                user.user_name = user_name
            if user_bio:
                user.bio = user_bio

            user.save()
            messages.info(request, '更新成功！')

        return render(request, 'profile.html', {"user": user})

    elif request.method == "GET":
        return render(request, 'profile.html', {"user": user})


def settings(request):
    user = request.user
    if not user.is_authenticated:
        messages.error(request, '请先登录！')
        return redirect("User:login")
    if request.method == 'POST':
        llm_category = request.POST.get('llm')
        api_key = request.POST.get('api')
        token = request.POST.get('token')
        temperature = request.POST.get('temperature')
        stage1 = request.POST.get('stage1')
        stage2 = request.POST.get('stage2')
        stage3 = request.POST.get('stage3')

        # print(type(llm_category))
        # print("llm_category", llm_category)
        # print("api_key", api_key)
        # print(type(token))
        # print(token)
        #
        # print(type(temperature))
        # print(temperature)
        # print(stage1)

        # 更新模型实例
        user_model = user.llm_model
        print(user_model.llm_category)
        user_model.llm_category = int(llm_category)
        if api_key:
            user_model.llm_api = api_key
        if token:
            user_model.llm_token = token
        if temperature:
            user_model.llm_temp = temperature
        user_model.stage1 = stage1
        user_model.stage2 = stage2
        user_model.stage3 = stage3
        user_model.save()
        user.save()

        messages.success(request, "设置已成功更新。")

        return render(request, 'settings.html', {"user": user})

    elif request.method == "GET":
        return render(request, 'settings.html', {"user": user})

User/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Login</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
<style>
@keyframes fade-in {
    from {
        opacity: 0;
    }
    to {
        opacity: 0.9;
    }
}

.fade-in-out {
    opacity: 0;
    animation: fade-in 1s forwards;
}
</style>

</head>

<body style="background-image: url('{% static '/img/banner.jpg' %}')!important;">

    <div class="fade-in-out">
        <div class="container">
            <!-- Outer Row -->
            <div class="row justify-content-center">

                <div class="col-xl-10 col-lg-12 col-md-9">

                    <div class="card o-hidden border-0 shadow-lg my-5">
                        <div class="card-body p-0">
                            <!-- Nested Row within Card Body -->
                            <div class="row">
                                <div class="col-lg-5 d-none d-lg-block bg-login-image">
                                    <img src="{% static '/img/login.gif' %}" alt="login" style="width: 350px; padding-left: 50px;padding-top: 50px">
                                </div>
                                <div class="col-lg-7">
                                    <div class="p-5">
                                        <div class="text-center">
                                            <h1 class="h4 text-gray-900 mb-4">欢迎使用 <strong>BinLLM</strong> !</h1>
                                        </div>
                                        <!-- 表单：获取用户名 + 密码 -->
                                        <form class="user" method="post">
                                            {% csrf_token %}
                                            <div class="form-group">
                                                <input type="email" class="form-control form-control-user" name="email"
                                                    id="exampleInputEmail" aria-describedby="emailHelp"
                                                    placeholder="请输入邮箱...">
                                            </div>
                                            <div class="form-group">
                                                <input type="password" class="form-control form-control-user" name="password"
                                                    id="exampleInputPassword" placeholder="密码">
                                            </div>
                                            <div class="form-group">
                                                <div class="custom-control custom-checkbox small">
                                                    <input type="checkbox" class="custom-control-input" id="customCheck">
                                                    <label class="custom-control-label" for="customCheck">记住我</label>
                                                </div>
                                            </div>

                                            <button class="btn btn-info btn-user btn-block" type="submit">
                                                登录
                                            </button>
    {#                                        <hr>#}
    {#                                        <a href="index.html" class="btn btn-google btn-user btn-block">#}
    {#                                            <i class="fab fa-google fa-fw"></i> Login with Google#}
    {#                                        </a>#}
    {#                                        <a href="index.html" class="btn btn-facebook btn-user btn-block">#}
    {#                                            <i class="fab fa-facebook-f fa-fw"></i> Login with Facebook#}
    {#                                        </a>#}
                                        </form>
                                        <hr>
                                        <div class="text-center">
                                            <a class="small" href="{% url 'User:register' %}">忘记密码？</a>
                                        </div>
                                        <div class="text-center">
                                            <a class="small" href="{% url 'User:register' %}">注册新的账户！</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

            </div>

        </div>
    </div>


    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>
{% if messages %}
<script>
    {% for msg in messages %}
        alert('{{ msg.message }}');
    {% endfor %}
</script>
{% endif %}
</body>

</html>

User/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Login</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
<style>
@keyframes fade-in {
    from {
        opacity: 0;
    }
    to {
        opacity: 0.9;
    }
}

.fade-in-out {
    opacity: 0;
    animation: fade-in 1s forwards;
}
</style>

</head>

<body style="background-image: url('{% static '/img/banner.jpg' %}')!important;">

    <div class="fade-in-out">
        <div class="container">
            <!-- Outer Row -->
            <div class="row justify-content-center">

                <div class="col-xl-10 col-lg-12 col-md-9">

                    <div class="card o-hidden border-0 shadow-lg my-5">
                        <div class="card-body p-0">
                            <!-- Nested Row within Card Body -->
                            <div class="row">
                                <div class="col-lg-5 d-none d-lg-block bg-login-image">
                                    <img src="{% static '/img/register.gif' %}" alt="login" style="width: 300px; padding-left: 80px;padding-top: 80px">
                                </div>
                                <div class="col-lg-7">
                                    <div class="p-5">
                                        <!-- 标题 -->
                                        <div class="text-center">
                                            <h1 class="h4 text-gray-900 mb-4">创建一个新的账户 ！</h1>
                                        </div>
                                        <!-- 表单：获取用户名 + 密码 -->
                                        <form class="user" method="post">
                                            {% csrf_token %}
                                            <div class="form-group">
                                                <input type="email" class="form-control form-control-user" name="email"
                                                    id="exampleInputEmail" aria-describedby="emailHelp"
                                                    placeholder="请输入邮箱...">
                                            </div>
                                            <div class="form-group">
                                                <input type="text" class="form-control form-control-user"
                                                    id="InputText"  name="user_name"
                                                    placeholder="请输入用户名...">
                                            </div>
                                            <div class="form-group row">
                                                <div class="col-sm-6 mb-3 mb-sm-0">
                                                    <input type="password" class="form-control form-control-user" name="password"
                                                        id="InputPassword" placeholder="密码">
                                                </div>
                                                <div class="col-sm-6">
                                                    <input type="password" class="form-control form-control-user" name="password2"
                                                        id="RepeatPassword" placeholder="确认密码">
                                                </div>
                                            </div>

                                            {% if check %}
{#                                            <div class="text-center">#}
{#                                                <p class="small">检查两次输入密码是否一致</p>#}
{#                                            </div>#}
                                            {% endif %}

                                            <button class="btn btn-info btn-user btn-block" type="submit">
                                                提交
                                            </button>

    {#                                        <hr>#}
    {#                                        <a href="index.html" class="btn btn-google btn-user btn-block">#}
    {#                                            <i class="fab fa-google fa-fw"></i> Login with Google#}
    {#                                        </a>#}
    {#                                        <a href="index.html" class="btn btn-facebook btn-user btn-block">#}
    {#                                            <i class="fab fa-facebook-f fa-fw"></i> Login with Facebook#}
    {#                                        </a>#}
                                        </form>
                                        <hr>

                                        <div class="text-center">
                                            <a class="small" href="{% url 'User:login' %}">使用已有的账户登录！</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

            </div>

        </div>
    </div>


    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>
{% if messages %}
<script>
    {% for msg in messages %}
        alert('{{ msg.message }}');
    {% endfor %}
</script>
{% endif %}


</body>


</html>